import styles from "../styles/stylesMainContainer.module.scss";

import Head from "next/head";
import Footer from "./Footer";
import Link from "next/link";

type TPropsMainContainer = {
  children: React.ReactNode;
  isLinkToMainPage?: boolean;
};

const MainContainer = (props: TPropsMainContainer) => {
  const { children, isLinkToMainPage } = props;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {isLinkToMainPage && (
          <Link href="/" passHref={true}>
            <a>To main page</a>
          </Link>
        )}

        <main className={styles.main}>{children}</main>

        <Footer />
      </div>
    </>
  );
};

export default MainContainer;
